

FROM python:3.9-slim

WORKDIR /app


COPY requirements_service.txt requirements.txt


RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8000

COPY server.py .
COPY test.html .
COPY index.html .
COPY ./knowledge_base_db ./knowledge_base_db

ENV GEMINI_API_KEY=""


CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]